name: Deploy to Cloud Run with Load Balancer

on:
  push:
    branches:
      - develop

env:
  PROJECT_ID: learned-maker-459200-v6
  REGION: us-central1
  SERVICE_NAME: hola-mundo
  REPO_NAME: cloud-run

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Authenticate with GCP
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Setup gcloud CLI
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ env.PROJECT_ID }}

    - name: Create Artifact Registry (si no existe)
      run: |
        gcloud artifacts repositories list --location=$REGION \
        | grep $REPO_NAME || \
        gcloud artifacts repositories create $REPO_NAME \
          --repository-format=docker \
          --location=$REGION \
          --description="Repo para Cloud Run"

    - name: Build and push Docker image
      run: |
        gcloud auth configure-docker $REGION-docker.pkg.dev
        docker build -t us-central1-docker.pkg.dev/PROJECT-ID/REPO/IMAGE .
        docker push us-central1-docker.pkg.dev/PROJECT-ID/REPO/IMAGE
        gcloud run deploy hola-mundo \
          --image=us-central1-docker.pkg.dev/PROJECT-ID/REPO/IMAGE \
          --region=us-central1 \
          --platform=managed \
          --allow-unauthenticated


    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy $SERVICE_NAME \
          --image=$REGION-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/$SERVICE_NAME \
          --platform=managed \
          --region=$REGION \
          --allow-unauthenticated

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Init & Apply
      working-directory: infra
      run: |
        terraform init
        terraform apply -auto-approve \
          -var="project_id=${{ env.PROJECT_ID }}" \
          -var="region=${{ env.REGION }}" \
          -var="image_url=$REGION-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/$SERVICE_NAME"

